services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    restart: on-failure
    command: mongod --auth 
    environment:
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: student
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ../data/race_taxi.csv:/docker-entrypoint-initdb.d/race_taxi.csv
      - ../data/race_bikes.csv:/docker-entrypoint-initdb.d/race_bikes.csv
      - ../data/race_crashes.csv:/docker-entrypoint-initdb.d/race_crashes.csv
      - ../data/taxi_timeseries.csv:/docker-entrypoint-initdb.d/taxi_timeseries.csv
      - ../data/bike_timeseries.csv:/docker-entrypoint-initdb.d/bike_timeseries.csv
      - ../data/crashes_timeseries.csv:/docker-entrypoint-initdb.d/crashes_timeseries.csv
      - ../data/taxi_heatmap.csv:/docker-entrypoint-initdb.d/taxi_heatmap.csv
      - ../data/bike_heatmap.csv:/docker-entrypoint-initdb.d/bike_heatmap.csv
      - ../data/crashes_heatmap.csv:/docker-entrypoint-initdb.d/crashes_heatmap.csv
      - ../data/pandemic_matrix.json:/docker-entrypoint-initdb.d/pandemic_matrix.json
      - ../data/pre_pandemic_matrix.json:/docker-entrypoint-initdb.d/pre_pandemic_matrix.json
      - ../data/post_pandemic_matrix.json:/docker-entrypoint-initdb.d/post_pandemic_matrix.json
      - ../data/pandemic_zones.json:/docker-entrypoint-initdb.d/pandemic_zones.json
      - ../data/pre_pandemic_zones.json:/docker-entrypoint-initdb.d/pre_pandemic_zones.json
      - ../data/post_pandemic_zones.json:/docker-entrypoint-initdb.d/post_pandemic_zones.json
      - ../data/pandemic_matrix_taxi.json:/docker-entrypoint-initdb.d/pandemic_matrix_taxi.json
      - ../data/pre_pandemic_matrix_taxi.json:/docker-entrypoint-initdb.d/pre_pandemic_matrix_taxi.json
      - ../data/post_pandemic_matrix_taxi.json:/docker-entrypoint-initdb.d/post_pandemic_matrix_taxi.json
      - ../data/pandemic_zones_taxi.json:/docker-entrypoint-initdb.d/pandemic_zones_taxi.json
      - ../data/pre_pandemic_zones_taxi.json:/docker-entrypoint-initdb.d/pre_pandemic_zones_taxi.json
      - ../data/post_pandemic_zones_taxi.json:/docker-entrypoint-initdb.d/post_pandemic_zones_taxi.json
      - ../data/bike_spiral.csv:/docker-entrypoint-initdb.d/bike_spiral.csv
      - ../data/taxi_spiral.csv:/docker-entrypoint-initdb.d/taxi_spiral.csv
      - ../data/crashes_spiral.csv:/docker-entrypoint-initdb.d/crashes_spiral.csv
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./database/mongo-update.sh:/docker-entrypoint-initdb.d/mongo-update.sh:ro
      - mongodbdata:/data/db
    networks:
      - backend

  server:
    build: ./server
    container_name: server
    hostname: backend
    command: python3 -u server.py
    restart: always
    environment:
      MONGODB_USERNAME: student
      MONGODB_PASSWORD: student
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE: project
    ports:
      - "5000:5000"
    volumes:
      - serverdata:/server/data
    depends_on:
      - mongodb
      - frontend
    networks:
      - backend
      - frontend
  
  frontend:
    build: ./frontend
    restart: always
    container_name: ui
    ports:
      - "80:80"
    networks:
      - frontend


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  serverdata:
    driver: local
