version: '3.7'
services:
  app:
    build: ./server
    container_name: server
    command: python3 -u server.py
    restart: unless-stopped
    environment:
      MONGODB_USERNAME: student
      MONGODB_PASSWORD: student
      MONGODB_HOSTNAME: mongodb
      MONGODB_DATABASE: project
    ports:
      - "5000:5000"
    volumes:
      - serverdata:/server/data
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: on-failure
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: student
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  serverdata:
    driver: local
